#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config gapless_monocle      true
bspc config automatic_scheme     longest_side
bspc config normal_border_color  #000000
bspc config active_border_color  #000000
bspc config focused_border_color #AAAAAA

$XDG_BIN_HOME/screen.sh -s $(xrandr | grep -w connected | wc -l)
