#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP1   -d 1 2 3 4
bspc monitor LVDS1 -d 5 6 7 8

bspc desktop DP1   -l tiled
bspc desktop LVDS1 -l tiled

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config automatic_scheme 	 longest_side


bspc rule -a brave desktop='^5'
