export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_BIN_HOME="$HOME/.local/bin"

# Default programs:
export EDITOR="vim"
export TERMINAL="st"
export READER="zathura"
export FILE="nnn"

# Misc
export HISTFILESIZE=10000
export HISTSIZE=10000
export LS_COLORS="or=31;40;05"
export PATH="$PATH:$XDG_BIN_HOME"
export PASSWORD_STORE_X_SELECTION="xclip -selection primary"

# Dotfiles
export BC_ENV_ARGS="$XDG_CONFIG_HOME/bc/bcrc"
export DISTCC_DIR="/var/tmp/portage/.distcc/"
export DOTREMINDERS="$XDG_DATA_HOME/remind/reminders"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export LESSHISTFILE="$XDG_CACHE_HOME/less"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"
export MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch/notmuchrc"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"
export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
export PYTHONPATH="PYTHONPATH:$XDG_CONFIG_HOME/python:/usr/lib/python3.7/site-packages:~/.local/lib/python3.7/site-packages"
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export XAPPLRESDIR="$XDG_CONFIG_HOME/gnuplot/config"
#export XAUTHORITY="$XDG_CONFIG_HOME/X11/.Xauthority"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
