.TH GERMAN "7" "June 2021" "Ultraconf" "Linux Programmer's Manual"
.SH NAME
german \- German Grammar Helpers

.SH DESCRIPTION

.SS Genders

Indicators for masculine words
.TS
l	l	l.
Word group / ending	Example	Annotation
_
-ig	König, Honig	Standard German pronunciation of -ig: [-ɪç]
-ling	Schmetterling, Günstling, Frühling	-
-ismus	Kapitalismus, Kommunismus	Often political/biological terms
-ist	Extremist, Anarchist	Usually people
-us	Usus, Anus	Only if of Latin origin
-iker	Akademiker, Theoretiker	Usually people
-ier	Offizier, Hellebardier	Usually people
-or	Rektor, Motor	-
-ör	Frisör, Likör	French origin
-eur	Friseur, Amateur	French origin
-ent	Dozent, Student	Usually people
-ant	Demonstrant, Informant	Usually people
-ast	Gymnasiast, Phantast	Usually people
-os	Pathos, Ethos	Only words of Greek origin
Male persons and animals	der Andreas, der Arzt, der Löwe	
Days	Montag, Dienstag, Mittwoch	-
Months	Januar, Februar, März, April	-
Seasons	Frühling, Sommer, Herbst, Winter	-
Weather	Regen, Sturm, Schnee, Wind	-
Directions	Norden, Süden, Westen, Osten	only geographical directions
Rocks and precious stones	Basalt, Saphir, Smaragd	most of them, there are exceptions
Mountains and mountainous regions	Harz, Brocken, Ätna	exceptions: compound words as well as die Eifel, die Haardt, die Rhön, die Sierra Nevada
Non-European rivers	Ganges, Nil, Mississippi	-
Car brands / cars	BMW, Golf, Ferrari	exception: die Corvette
Alcoholic and plant-based drinks	Wodka, Martini, Saft	exception: das Bier
Nouns formed from the stem of strong verbs	betreiben (betrieb, betrieben) --> Trieb	exception: das Schloss
Monetary units	Dollar, Gulden, Taler	
.TE

Indicators for feminine words
.TS
l	l	l.
Word group / ending	Example	Annotation
_
-ung	Leistung, Erzählung, Bedeutung	-
-in	Bäckerin, Polizistin	Usually jobs
-keit	Heiterkeit, Schwierigkeit	-
-ei	Bücherei, Bäckerei, Partei	-
-heit	Freiheit, Gleichheit	-
-schaft	Anwaltschaft, Mannschaft	-
-ade	Marmelade, Panade	often words of foreign origin
-ie	Demokratie, Theorie	often -y in English
-ion	Dimension, Tradition	-
-ik	Musik, Kritik	-
-ine	Maschine, Lawine, Gardine	-
-ive	Offensive, Defensive	-
-itis	Meningitis, Bronchitis	often diseases
-isse	Kulisse, Abszisse	words of foreign origin only
-a	Kamera, Aula	usually words of Latin origin
-anz	Toleranz, Bilanz	words of foreign origin only
-enz	Karenz, Exzellenz	words of foreign origin only
-ette	Toilette, Gazette	words of foreign origin only
-sis	Skepsis, Basis	-
-tät	Realität, Banalität	often -ity in English
-ur	Natur, Kultur, Zensur	words of foreign origin only
-e	Fresse, Ehe	about 90% of words ending in -e
Female persons and animals	Kuh, Frau, Ärztin	exception: das Mädchen (diminutive)
Ships	Titanic, Gorch Fock, Bismarck	due to the traditionally female names of ships
Motorcycles	Ducati, Mitsubishi, Harley	-
Airplanes	Focker, Boeing, B-52	exception: der Airbus, der Eurofighter
Trees	Eiche, Linde, Tanne	exception: der Ahorn
European rivers	die Themse, die Seine, die Donau	exception: der Po, der Rhein, der Neckar
Numbers	die Eins, die Million, die Tausend	-
.TE

Indicators for neuter words
.TS
l	l	l.
Word group / ending	Example	Annotation
_
-chen	Mädchen, Hündchen	Diminutive
-lein	Fräulein, Menschlein	Diminutive, tends to be more common in the South
-tum	Bistum, Eigentum	English -dom words often translate to -tum.
-um	Datum, Album	-
-in	Benzin, Hämoglobin	-
-ing	Doping, Marketing	mostly English words
-icht	Gewicht, Gesicht	-
-eau	Niveau, Plateau	of French origin
-o	Büro, Auto	-
-ett	Tablett, Ballett	-
-at	Mandat, Substrat, Karat	exception: die Tat
-ma	Klima, Komma, Schisma	exception: die Firma
-ment	Firmament, Dokument	-
-nis	Zeugnis, Gefängnis	-
- tel	Drittel, Viertel, Fünftel	-
Letters	A, B, C	both alphabet and music
Colours	Rot, Blau,Grün	-
Hotels, cafés, restaurants	Atlantic, Michel, Vapiano	-
Cinemas	Cinemaxx, Cineworld	-
Metals and chemical elements	Blei, Gold, Eisen	exceptions: die Bronze, der Phosphor, -stoff elements
Scientific units	Ohm, Meter, Ampere	Meter and Liter are masculine in coll. speech
Diminutives	Mädchen, Hündchen, Menschlein	Apart from -chen and -lein, there is also a huge variety of dialectal diminutives.
Nominalised infinitives	das Lesen, das Schreiben, das Schwimmen	-
.TE

.SS Articles Definite
.TS
l	l	l	l.
	Masculine	Feminine	Neuter	Plural
_
Nominative	der	die	das	die
Accusative	den	die	das	die
Dative	dem	der	dem	den (n)
Genitive	des (s,es)	der	des (s,es)	der
.TE


.SS Articles Indefinite
.TS
l	l	l	l.
	Masculine	Feminine	Neuter	Plural
_
Nominative	ein	eine	ein	-eine
Accusative	einen	eine	ein	-eine
Dative	einem	einer	einem	-einen
Genitive	eines	einer	eines	-einer
.TE

.SS Personal pronouns
.TS
l	l	l	l
l	l	l	l	l	l	l	l	l	l.
	Singular					Plural			Formal
Case	First	Second	Third			First	Second	Third	Second
_
Nominative	ich	du	er	es	sie	wir	ihr	sie	Sie
Accusative	mich	dich	ihn	es	sie	uns	euch	sie	Sie
Dative	mir	dir	ihm	ihm	ihr	uns	euch	ihnen	Ihnen
Genitive	meiner	deiner	seiner	seiner	ihrer	unser	euer	ihrer	Ihrer
.TE

.SS Prepositions

.TS
l	l	l.
Accusative	Dative	Genitive
_
bis (until, up to, as far as)	aus (out of)	anstatt/statt (instead [of])
durch (through, by means of)	außer (except for)	während (during)
für (for)	gegenüber (opposite of, toward someone, across from)	trotz (despite)
ohne (without)	bei (at)	wegen (because of)
gegen (against)	mit (with)	außerhalb (outside of)
um (around, at [a certain] time, for)	nach (after, to, according to)	innerhalb (inside of)
entlang (along)	seit (since, for—only)	oberhalb (above)
	zu (to)	unterhalb (below)
	von (from)	diesseits (on this side)
		jenseits (on the other side)
		beiderseits (on both sides)
.TE

.SH AUTHORS
Inspired from https://www.reddit.com/r/German/wiki/grammar
			  https://en.wikipedia.org/wiki/German_pronouns
