.TH JIRA_SYNTAX "7" "May 2021" "Ultraconf" "Linux Programmer's Manual"
.SH NAME
jira syntax \- Text Formatting Notation Help

.SH DESCRIPTION

.SS Headings

To create a header, place "hn. " at the start of the line (where n can be
a number from 1-6).

.TS
l	l.
Notation	Comment
_
h1. Biggest heading	Biggest heading
h2. Bigger heading	Bigger heading
h3. Big heading	Big heading
h4. Normal heading	Normal heading
h5. Small heading	Small heading
h6. Smallest heading	Smallest heading
.TE

.SS Text Effects

Text effects are used to change the formatting of words and sentences.

.TS
l	l.
Notation	Comment
_
*strong*	Makes text strong.
_emphasis_	Makes text emphasis..
??citation??	Makes text in citation.
-deleted-	Makes text as deleted.
+inserted+	Makes text as inserted.
^superscript^	Makes text in ^superscript.
~subscript~	Makes text in [subscript].
{{monospaced}}	Makes text as monospaced.
bq. Some block quoted text	To make an entire paragraph into a block
	quotation, place "bq. " before it.

{quote}	Quote a block of text that's longer than one
    here is quotable	paragraph.
 content to be quoted	
{quote}	

{color:red}	Changes the color of a block of text.
    look ma, red text!
{color}
.TE

.SS Text Breaks

Most of the time, explicit paragraph breaks are not required - The wiki
renderer will be able to paginate your paragraphs properly.

.TS
l	l.
Notation	Comment
_
(empty line)	Produces a new paragraph
\\	Creates a line break. Not often needed, most of the time the
	wiki renderer will guess new lines for you appropriately.

----	Creates a horizontal ruler.
---	Produces — symbol.
--	Produces – symbol.
.TE

.SS Links

Learning how to create links quickly is important.

.TS
l	l.
Notation	Comment
_
[#anchor]	Creates an internal hyperlink to
[^attachment.ext]	the specified anchor or
	attachment. Appending the '#' sign
	followed by an anchor name will
	lead into a specific bookmarked
	point of the desired page. Having
	the '^' followed by the name of an
	attachment will lead into a link
	to the attachment of the current
	issue.

[http://jira.atlassian.com]	Creates a link to an external
[Atlassian|http://atlassian.com]	resource, special characters that
	come after the URL and are not
	part of it must be separated with
	a space.
	The [] around external links are
	optional in the case you do not
	want to use any alias for the
	link.

[mailto:legendaryservice@atlassian.com]	Creates a link to an email
	address, complete with mail icon.

[file:///c:/temp/foo.txt]	Creates a download link to a file
[file:///z:/file/on/network/share.txt]	on your computer or on a network
	share that you have mapped to a
	drive. To access the file, you
	must right click on the link and
	choose "Save Target As".

{anchor:anchorname}	By default, this only works on
	Internet Explorer but can also be
	enabled in Firefox (see docs).
	Creates a bookmark anchor inside
	the page. You can then create
	links directly to that anchor. So
	the link [My Page#here] will link
	to wherever in "My Page" there is
	an {anchor:here} macro, and the
	link [#there] will link to
	wherever in the current page there
	is an {anchor:there} macro.

[~username]	Creates a link to the user profile
	page of a particular user, with a
	user icon and the user's full
	name.
.TE

.SS Lists

Lists allow you to present information as a series of ordered items.

.TS
l	l.
Notation	Comment
_
* some	A bulleted list (must be in first column). Use more (**) for
* bullet	deeper indentations.
** indented
** bullets	Example:
* points	● some
	● bullet
	  ○ indented
	  ○ bullets
	● points

- different	A list item (with -), several lines create a single list.
- bullet	Example:
- types	• different
	• bullet
	• types

# a	A numbered list (must be in first column). Use more (##, ###)
# numbered	for deeper indentations.
# list	Example:
	1. a
	2. numbered
	3. list

# a	You can even go with any kind of mixed nested lists
# numbered
#* with	Example:
#* nested	1. a
#* bullet	2. numbered      
# list	  ○ with
	  ○ nested
	  ○ bullet
	3. list

* a	Example:
* bulleted	● a
*# with	● bulleted
*# nested	  1. with 
*# numbered	  2. nested 
* list	  3. numbered
	● list
.TE

.SS Images

Images can be embedded into a wiki renderable field from attached files or
remote sources.

.TS
l	l.
Notation	Comment
_
!http://www.host.com/image.gif!	Inserts an image into the page.
or                                
!attached-image.gif!	If a fully qualified URL is given the
	image will be displayed from the remote
	source, otherwise an attached image file
	is displayed.
!image.jpg|thumbnail!	Insert a thumbnail of the image into the
	page (only works with images that are
	attached to the page).
!image.gif|align=right, vspace=4!	For any image, you can also specify
	attributes of the image tag as a comma
	separated list of name=value pairs like so.
.TE

.SS Attachments

Some attachments of a specific type can be embedded into a wiki renderable
field from attached files.

.TS
l	l.
Notation	Comment
_
!quicktime.mov!	Embeds an object in a page, taking in
!spaceKey:pageTitle^attachment.mov!	a comma-separated of properties.
!quicktime.mov|width=300,height=400!
!media.wmv|id=media!	Default supported formats:
	• Flash (.swf)
	• Quicktime movies (.mov)
	• Windows Media (.wma, .wmv)
	• Real Media (.rm, .ram)
	• MP3 files (.mp3)

	Other types of files can be used, but
	may require the specification of the
	"classid", "codebase" and
	"pluginspage" properties in order to
	be recognised by web browsers.

	Common properties are:
	
	• width - the width of the media
	file
	• height - the height of the media
	file
	• id - the ID assigned to the
	embedded object

	Due to security issues, files located
	on remote servers are not permitted
	Styling
	By default, each embedded object is
	wrapped in a "div" tag. If you wish
	to style the div and its contents,
	override the "embeddedObject" CSS
	class. Specifying an ID as a property
	also allows you to style different
	embedded objects differently. CSS
	class names in the format
	"embeddedObject-ID" are used.
.TE

.SS Tables

Tables allow you to organise content in a rows and columns, with a header
row if required.

.TS
l	l.
Notation	Comment
_
||heading 1||heading 2||heading 3||	Makes a table. Use double bars for a
|col A1|col A2|col A3|	table heading row.
|col B1|col B2|col B3|
	The code given here produces a table
	that looks like:
	
	heading 1 heading 2 heading 3
	col A1    col A2    col A3
	col B1    col B2    col B3
.TE

.SS Advanced Formatting

More advanced text formatting.

.TS
l	l.
Notation	Comment
_
 {noformat}	Makes a preformatted block of text with no syntax highlighting. All
 preformatted piece of text	the optional parameters of {panel} macro are valid for {noformat}
  so *no* further _formatting_ is done here	too.
 {noformat}                                 
	• nopanel: Embraces a block of text within a fully customizable
	panel. The optional parameters you can define are the following
	ones:

	Example:

	preformatted piece of text so *no* further _formatting_ is done here

{panel}	Embraces a block of text within a fully customizable panel. The
Some text	optional parameters you can define are the following ones:
{panel}  
	• title: Title of the panel
{panel:title=My Title}	• borderStyle: The style of the border this panel uses (solid,
Some text with a title	dashed and other valid CSS border styles)
{panel}	• borderColor: The color of the border this panel uses
	• borderWidth: The width of the border this panel uses
	• bgColor: The background color of this panel
{panel:title=My Title|borderStyle=dashed|borderColor=#ccc|titleBGColor=#F7D6C1|bgColor=#FFFFCE}	• titleBGColor: The background color of the title section of this
a block of text surrounded with a *panel*	panel
yet _another_ line
{panel}	Example:

	My Title
	a block of text surrounded with a panel
	yet another line

{code:title=Bar.java|borderStyle=solid}	Makes a preformatted block of code with syntax highlighting. All the
// Some comments here	optional parameters of {panel} macro are valid for {code} too. The
public String getFoo()	default language is Java but you can specify others too, including
{	ActionScript, Ada, AppleScript, bash, C, C#, C++, CSS, Erlang, Go,
    return foo;	Groovy, Haskell, HTML, JavaScript, JSON, Lua, Nyan, Objc, Perl, PHP,
}	Python, R, Ruby, Scala, SQL, Swift, VisualBasic, XML and YAML.
{code}
.TE


.SS Misc

Various other syntax highlighting capabilities.

.TS
l	l.
Notation	Comment
_
\\X	Escape special character X (i.e. {)
:)	Graphical emoticons (smileys).
	Notation :) :( :P :D ;)  (y) (n) (i) (/) (x) (!)
	Image    🙂 ☹️  😛 😁 😉  👍  👎  ℹ️   ✅  ❌  ⚠️         
:(	Notation (+) (-) (?) (on) (off) (*) (*r) (*g) (*b) (*y) (flag)
	Image    ➕  ➖  ❓  💡    💡   ⭐  ⭐   ⭐   ⭐   ⭐    🚩
etc	Notation (flagoff)
	Image    🏳️
.TE

.SH AUTHORS
From https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all
