filetype plugin indent on
syntax on
runtime ftplugin/man.vim
set keywordprg=:Man

exec "set list listchars=tab:\u258F\\\u20,trail:\u2508,nbsp:\uA4"
set autowriteall autoread
set background=dark
set cino+=(0g0
set completeopt-=preview
set cscopetag cscoperelative "cscopequickfix=s-,c-,d-,i-,t-,e-,a-
set diffopt+=iwhiteall,algorithm:patience,indent-heuristic diffopt-=internal
set encoding=utf8
set expandtab tabstop=4 shiftwidth=4 smarttab softtabstop=0 autoindent
set formatoptions-=o
set grepprg=grep\ -In\ --exclude=tags\ --exclude-dir=.svn
set history=1000 undofile viminfofile=$XDG_DATA_HOME/vim/viminfo viminfo='1000,<50,s10,h
set hlsearch incsearch showmatch
set keywordprg=:Man
set mouse=
set nocompatible nomodeline nowrap
set number relativenumber
set path+=**
set runtimepath=$XDG_CONFIG_HOME/vim,/usr/share/vim/vimfiles,$VIMRUNTIME
set scrolloff=10
set t_Co=256
set undodir=$XDG_DATA_HOME/vim/undo directory=$XDG_DATA_HOME/vim/swap backupdir=$XDG_DATA_HOME/vim/backup viewdir=$XDG_DATA_HOME/vim/view
set virtualedit=block
set wildmenu showcmd

let g:netrw_banner = 0
let g:netrw_sort_sequence = '[\/]$'
let g:netrw_preview = 1
let g:OmniCpp_DisplayMode = 1
let g:OmniCpp_ShowPrototypeInAbbr = 1
let g:OmniCpp_NamespaceSearch = 1

nnoremap g<C-]> :cs find 0 <C-R>=expand("<cword>")<CR><CR>
nnoremap g<C-\> :cs find 3 <C-R>=expand("<cword>")<CR><CR>
nnoremap gz :wall<CR>
nnoremap gH :noh<CR>
inoremap jk <esc>

hi DiffAdd      cterm=none      ctermfg=0        ctermbg=darkgreen
hi DiffChange   cterm=none      ctermfg=white    ctermbg=darkblue
hi DiffDelete   cterm=none      ctermfg=0        ctermbg=darkred
hi DiffText     cterm=none      ctermfg=darkblue ctermbg=white
hi MatchParen   cterm=none      ctermbg=darkgrey ctermfg=black
hi PmenuSel     ctermfg=black   ctermbg=white
hi QuickFixLine ctermbg=darkred
hi Special      ctermfg=darkred ctermbg=black

if filereadable(expand("$XDG_CONFIG_HOME/vim/addi.vim"))
    source $XDG_CONFIG_HOME/vim/addi.vim
    autocmd BufNewFile,BufRead COMMIT_EDITMSG inoremap <F2> <C-R>=Jid()<CR>
endif

autocmd BufNewFile,BufRead neomutt-*,COMMIT_EDITMSG,*.tex setlocal spell
autocmd BufNewFile,BufRead *.jira setlocal syntax=jira spell laststatus=2
autocmd BufNewFile,BufRead,BufEnter *.h,*.hpp,*.c,*.cc,*.cpp set omnifunc=omni#cpp#complete#Main
autocmd BufNewFile,BufRead *.~,*.txt,*.vhdl set nolist
if filereadable("./cscope.out")
    cscope add cscope.out
endif

command! Bro   enew! | setl  buftype=nofile | 0put =v:oldfiles | exe "silent % !fzy" | norm gf
command! Vbro  vnew   +setl\ buftype=nofile | 0put =v:oldfiles | exe "silent % !fzy" | norm gf
command! Sbro  new    +setl\ buftype=nofile | 0put =v:oldfiles | exe "silent % !fzy" | norm gf
command! Make  wa | silent make | redraw! | cw
command! Ctags !ctags -R --c++-kinds=+pl --fields=+iaS --extras=+q
